version: '3.9'

services:
  sonar_api:
    build: sonar_api
    container_name: sonar_api
    hostname: sonar_api
    volumes:
      - ./sonar_api:/sonar_api
    depends_on:
      - fluentd
      - mongo
      - redis
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.sonar
    networks:
      - mongonet
      - redisnet
      - cameranet

  camera_api:
    build: camera_api
    container_name: camera_api
    hostname: camera_api
    volumes:
      - ./camera_api:/camera_api
    environment:
      FLASK_APP: app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    depends_on:
      - fluentd
      - redis
      - mongo
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.camera
    networks:
      - mongonet
      - redisnet
      - cameranet

  mongoexpress:
    image: mongo-express:0.54.0
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_OPTIONS_EDITORTHEME: "dracula"
      ME_CONFIG_MONDODB_URL: mongodb://dbuser:dbpass@mongo:27017
      ME_CONFIG_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass
    depends_on:
      - mongo
    networks:
      - mongonet

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: cars
    networks:
      - mongonet

  redis:
    image: redis
    container_name: redis
    hostname: redis
    networks:
      - redisnet

  fluentd:
    build: logs
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./logs/conf:/fluentd/etc
    depends_on:
      - mongo
    networks:
      - mongonet
      - cameranet
      - sonarnet

networks:
  mongonet:
    name: mongonet
  redisnet:
    name: redisnet
  cameranet:
    name: cameranet
  sonarnet:
    name: sonarnet
