version: '3.9'

services:
  client:
    build: self-driving-car-interface
    container_name: car-interface
    hostname: car-interface
    volumes:
      - ./self-driving-car-interface:/app
    environment:
      NODE_APP: self-driving-car-interface
      NODE_ENV: development
    depends_on:
      - rest
    networks:
      - datacenternet

  rest:
    build: api
    container_name: rest
    hostname: rest
    volumes:
      - ./api:/api
    depends_on:
      - fluentd
      - mongo
      - redis
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.rest
    networks:
      - dbnet
      - datacenternet

  mongoexpress:
    image: mongo-express:0.54.0
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_OPTIONS_EDITORTHEME: "dracula"
      ME_CONFIG_MONDODB_URL: mongodb://dbuser:dbpass@mongo:27017
      ME_CONFIG_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass
    depends_on:
      - mongo
    networks:
      - dbnet

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: cars
    networks:
      - dbnet

  redis:
    image: redis
    container_name: redis
    hostname: redis
    networks:
      - dbnet

  fluentd:
    build: logs
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./logs/conf:/fluentd/etc
    depends_on:
      - mongo
    networks:
      - dbnet

networks:
  datacenternet:
    name: datacenternet
  dbnet:
    name: dbnet
