version: '3.9'

services:
  sonar:
    image: node:17-alpine3.13
    container_name: car_sonar
    hostname: sonar

  camera:
    image: python:3.11.0a1-alpine3.14
    container_name: car_camera
    hostname: camera

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: cars
    networks:
      - mongonet

  # TODO: Learn Redis
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    # enviroment:
    networks:
      - redisnet

  fluentd:
    build: logs
    container_name: fluentd
    volumes:
      - ./logs/conf:/fluentd/etc
    depends_on:
      - mongo
    networks:
      - mongonet

networks:
  mongonet:
    name: mongonet
  redisnet:
    name: redisnet